// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvd-GM3K_rXhu-EuiBqp6KK7XsujKW_WQ',
    appId: '1:531033211381:web:4bfde968bd19323d73a0bc',
    messagingSenderId: '531033211381',
    projectId: 'e-commerce-app-41266',
    authDomain: 'e-commerce-app-41266.firebaseapp.com',
    storageBucket: 'e-commerce-app-41266.appspot.com',
    measurementId: 'G-HLGPDBNVS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyH5OJV0fhcCYZzN5eaDA1SpubI15JFKI',
    appId: '1:531033211381:android:c4764e70199c7ebe73a0bc',
    messagingSenderId: '531033211381',
    projectId: 'e-commerce-app-41266',
    storageBucket: 'e-commerce-app-41266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDxNGl4ntj0MuzbIjXW-15I5zf3HhpX-s',
    appId: '1:531033211381:ios:953cd8b31daa832b73a0bc',
    messagingSenderId: '531033211381',
    projectId: 'e-commerce-app-41266',
    storageBucket: 'e-commerce-app-41266.appspot.com',
    iosClientId: '531033211381-mdnor4j25shnapkt6j24ddbuforgd7kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDxNGl4ntj0MuzbIjXW-15I5zf3HhpX-s',
    appId: '1:531033211381:ios:953cd8b31daa832b73a0bc',
    messagingSenderId: '531033211381',
    projectId: 'e-commerce-app-41266',
    storageBucket: 'e-commerce-app-41266.appspot.com',
    iosClientId: '531033211381-mdnor4j25shnapkt6j24ddbuforgd7kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
